name: "Publish Docker Image to GitHub Registry"
description: "GitHub Action to build and subsequently publish Docker Image to GitHub Registry"
inputs:
  github-token:
    description: "GitHub token to push Docker image to GitHub Packages"
    required: true
  image-name:
    description: "Docker Image name"
    required: true
  image-tag:
    description: "Docker Image tag"
    default: "latest"
    required: false
  extract-git-tag:
    description: "Extract git-tag from repository"
    default: "false"
    required: false
  dockerfile-path:
    description: "Path to the Dockerfile to build"
    default: "Dockerfile"
    required: false
  context-dir:
    description: "Path to the directory where to execute your Dockerfile from"
    default: "."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.image-name }}
    - ${{ inputs.image-tag }}
    - ${{ inputs.extract-git-tag }}
    - ${{ inputs.dockerfile-path }}
    - ${{ inputs.context-dir }}
branding:
  icon: "box"
  color: "blue"
